CREATE DATABASE IF NOT EXISTS landingCalaPoint
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE landingCalaPoint;

CREATE TABLE IF NOT EXISTS emails (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  email VARCHAR(255) NOT NULL,
  source VARCHAR(100) DEFAULT NULL,
  status ENUM('new', 'contacted', 'converted') NOT NULL DEFAULT 'new',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY unique_email (email)
);
